/mnt/c/Users/Harsh/PycharmProjects/PythonForDevops/D9\ Subprocess/monitor.log {
    su harshkad harshkad
    daily
    rotate 7
    compress
    missingok
    notifempty
    create 0644 harshkad harshkad
}

